---
title: "Join"
---

**PhD opportunities.**

- 4-year [PhD position in multiscale modeling of polymers](https://academicpositions.com/ad/ku-leuven/2025/phd-position-in-multiscale-modeling-of-polymers/231118)

- [CSC-KU Leuven Scholarship Programme](https://set.kuleuven.be/phd/applicants/csc)

- [Baekeland mandates](https://www.vlaio.be/en/subsidies/baekeland-mandates)

- <p>For further information, <a href="mailto:riccardo.alessandri@kuleuven.be">please reach out</a>.</p>


**Postdoc opportunities.**

- [MSCA Postdoctoral Fellowships](https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships)

- [FWO Postdoctoral Fellowships](https://www.fwo.be/en/support-programmes/postdoctoral-fellowships/)

- <p>For further information, <a href="mailto:riccardo.alessandri@kuleuven.be">please reach out</a>.</p>


**Master's research internship opportunities.**

- Our Group hosts [TCCM](https://www.emtccm.org) Master's research internships - don't hesitate to <a href="mailto:riccardo.alessandri@kuleuven.be">reach out</a> if interested in carrying out your TCCM internship in our Group.

- KU Leuven Master student interested in doing a research internship with us? <a href="mailto:riccardo.alessandri@kuleuven.be">Reach out</a> to hear about current available projects.

- Interested in doing your Master research internship with us? <a href="mailto:riccardo.alessandri@kuleuven.be">Reach out</a> to hear about current available projects.


**Bachelor's research internship opportunities.**

- KU Leuven Bachelor student interested in doing a research internship with us? <a href="mailto:riccardo.alessandri@kuleuven.be">Reach out</a> to hear about current available projects.

- Interested in doing your Bachelor research internship with us? <a href="mailto:riccardo.alessandri@kuleuven.be">Reach out</a> to hear about current available projects.
